// source: ibc/core/client/v1/genesis.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var ibc_core_client_v1_client_pb = require('../../../../ibc/core/client/v1/client_pb.js');
goog.object.extend(proto, ibc_core_client_v1_client_pb);
var gogoproto_gogo_pb = require('../../../../gogoproto/gogo_pb.js');
goog.object.extend(proto, gogoproto_gogo_pb);
goog.exportSymbol('proto.ibc.core.client.v1.GenesisState', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ibc.core.client.v1.GenesisState = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.ibc.core.client.v1.GenesisState.repeatedFields_, null);
};
goog.inherits(proto.ibc.core.client.v1.GenesisState, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ibc.core.client.v1.GenesisState.displayName = 'proto.ibc.core.client.v1.GenesisState';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.ibc.core.client.v1.GenesisState.repeatedFields_ = [1,2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ibc.core.client.v1.GenesisState.prototype.toObject = function(opt_includeInstance) {
  return proto.ibc.core.client.v1.GenesisState.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ibc.core.client.v1.GenesisState} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ibc.core.client.v1.GenesisState.toObject = function(includeInstance, msg) {
  var f, obj = {
    clientsList: jspb.Message.toObjectList(msg.getClientsList(),
    ibc_core_client_v1_client_pb.IdentifiedClientState.toObject, includeInstance),
    clientsConsensusList: jspb.Message.toObjectList(msg.getClientsConsensusList(),
    ibc_core_client_v1_client_pb.ClientConsensusStates.toObject, includeInstance),
    createLocalhost: jspb.Message.getBooleanFieldWithDefault(msg, 3, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ibc.core.client.v1.GenesisState}
 */
proto.ibc.core.client.v1.GenesisState.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ibc.core.client.v1.GenesisState;
  return proto.ibc.core.client.v1.GenesisState.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ibc.core.client.v1.GenesisState} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ibc.core.client.v1.GenesisState}
 */
proto.ibc.core.client.v1.GenesisState.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new ibc_core_client_v1_client_pb.IdentifiedClientState;
      reader.readMessage(value,ibc_core_client_v1_client_pb.IdentifiedClientState.deserializeBinaryFromReader);
      msg.addClients(value);
      break;
    case 2:
      var value = new ibc_core_client_v1_client_pb.ClientConsensusStates;
      reader.readMessage(value,ibc_core_client_v1_client_pb.ClientConsensusStates.deserializeBinaryFromReader);
      msg.addClientsConsensus(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setCreateLocalhost(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ibc.core.client.v1.GenesisState.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ibc.core.client.v1.GenesisState.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ibc.core.client.v1.GenesisState} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ibc.core.client.v1.GenesisState.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getClientsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      ibc_core_client_v1_client_pb.IdentifiedClientState.serializeBinaryToWriter
    );
  }
  f = message.getClientsConsensusList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      ibc_core_client_v1_client_pb.ClientConsensusStates.serializeBinaryToWriter
    );
  }
  f = message.getCreateLocalhost();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
};


/**
 * repeated IdentifiedClientState clients = 1;
 * @return {!Array<!proto.ibc.core.client.v1.IdentifiedClientState>}
 */
proto.ibc.core.client.v1.GenesisState.prototype.getClientsList = function() {
  return /** @type{!Array<!proto.ibc.core.client.v1.IdentifiedClientState>} */ (
    jspb.Message.getRepeatedWrapperField(this, ibc_core_client_v1_client_pb.IdentifiedClientState, 1));
};


/**
 * @param {!Array<!proto.ibc.core.client.v1.IdentifiedClientState>} value
 * @return {!proto.ibc.core.client.v1.GenesisState} returns this
*/
proto.ibc.core.client.v1.GenesisState.prototype.setClientsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.ibc.core.client.v1.IdentifiedClientState=} opt_value
 * @param {number=} opt_index
 * @return {!proto.ibc.core.client.v1.IdentifiedClientState}
 */
proto.ibc.core.client.v1.GenesisState.prototype.addClients = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.ibc.core.client.v1.IdentifiedClientState, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.ibc.core.client.v1.GenesisState} returns this
 */
proto.ibc.core.client.v1.GenesisState.prototype.clearClientsList = function() {
  return this.setClientsList([]);
};


/**
 * repeated ClientConsensusStates clients_consensus = 2;
 * @return {!Array<!proto.ibc.core.client.v1.ClientConsensusStates>}
 */
proto.ibc.core.client.v1.GenesisState.prototype.getClientsConsensusList = function() {
  return /** @type{!Array<!proto.ibc.core.client.v1.ClientConsensusStates>} */ (
    jspb.Message.getRepeatedWrapperField(this, ibc_core_client_v1_client_pb.ClientConsensusStates, 2));
};


/**
 * @param {!Array<!proto.ibc.core.client.v1.ClientConsensusStates>} value
 * @return {!proto.ibc.core.client.v1.GenesisState} returns this
*/
proto.ibc.core.client.v1.GenesisState.prototype.setClientsConsensusList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.ibc.core.client.v1.ClientConsensusStates=} opt_value
 * @param {number=} opt_index
 * @return {!proto.ibc.core.client.v1.ClientConsensusStates}
 */
proto.ibc.core.client.v1.GenesisState.prototype.addClientsConsensus = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.ibc.core.client.v1.ClientConsensusStates, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.ibc.core.client.v1.GenesisState} returns this
 */
proto.ibc.core.client.v1.GenesisState.prototype.clearClientsConsensusList = function() {
  return this.setClientsConsensusList([]);
};


/**
 * optional bool create_localhost = 3;
 * @return {boolean}
 */
proto.ibc.core.client.v1.GenesisState.prototype.getCreateLocalhost = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!proto.ibc.core.client.v1.GenesisState} returns this
 */
proto.ibc.core.client.v1.GenesisState.prototype.setCreateLocalhost = function(value) {
  return jspb.Message.setProto3BooleanField(this, 3, value);
};


goog.object.extend(exports, proto.ibc.core.client.v1);
